#
# version.cmake : version du projet
#

set (PLUGIN_MAJOR_VERSION "6")
set (PLUGIN_MINOR_VERSION "0")
set (PLUGIN_RELEASE_VERSION "0")
set (PLUGIN_VERSION ${PLUGIN_MAJOR_VERSION}.${PLUGIN_MINOR_VERSION}.${PLUGIN_RELEASE_VERSION})


