#
# version.cmake : version du projet
#

set (QT_NETWORK_MAJOR_VERSION "6")
set (QT_NETWORK_MINOR_VERSION "0")
set (QT_NETWORK_RELEASE_VERSION "0")
set (QT_NETWORK_VERSION ${QT_NETWORK_MAJOR_VERSION}.${QT_NETWORK_MINOR_VERSION}.${QT_NETWORK_RELEASE_VERSION})


