#
# version.cmake : version du projet
#

set (CORBA_UTIL_MAJOR_VERSION "6")
set (CORBA_UTIL_MINOR_VERSION "1")
set (CORBA_UTIL_RELEASE_VERSION "0")
set (CORBA_UTIL_VERSION ${CORBA_UTIL_MAJOR_VERSION}.${CORBA_UTIL_MINOR_VERSION}.${CORBA_UTIL_RELEASE_VERSION})

