#
# version.cmake : version du projet
#

set (GUI_TOOLKITS_MAJOR_VERSION "1")
set (GUI_TOOLKITS_MINOR_VERSION "6")
set (GUI_TOOLKITS_RELEASE_VERSION "0")
set (GUI_TOOLKITS_VERSION ${GUI_TOOLKITS_MAJOR_VERSION}.${GUI_TOOLKITS_MINOR_VERSION}.${GUI_TOOLKITS_RELEASE_VERSION})
