#
# version.cmake : version du projet
#

set (GUI_TOOLKITS2_MAJOR_VERSION "1")
set (GUI_TOOLKITS2_MINOR_VERSION "2")
set (GUI_TOOLKITS2_RELEASE_VERSION "0")
set (GUI_TOOLKITS2_VERSION ${GUI_TOOLKITS2_MAJOR_VERSION}.${GUI_TOOLKITS2_MINOR_VERSION}.${GUI_TOOLKITS2_RELEASE_VERSION})

