#
# version.cmake : version du projet
#

set (ANNOTATIONS_MAJOR_VERSION "3")
set (ANNOTATIONS_MINOR_VERSION "0")
set (ANNOTATIONS_RELEASE_VERSION "0")
set (ANNOTATIONS_VERSION ${ANNOTATIONS_MAJOR_VERSION}.${ANNOTATIONS_MINOR_VERSION}.${ANNOTATIONS_RELEASE_VERSION})


