name: Spack CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call:
    name: Call Spack reusable workflow
    uses: LIHPC-Computational-Geometry/lihpccg-ci/.github/workflows/spack-reusable.yml@main
    with:
      test-link-options: "-DUSE_PYTHON_3:BOOL=ON -DTK_UTIL:BOOL=ON -DPYTHON_UTIL:BOOL=ON -DQT_UTIL:BOOL=ON -DQT_PYTHON:BOOL=ON -DPREFERENCES:BOOL=ON -DQWT_CHARTS:BOOL=ON -DQQUALIF:BOOL=ON -DVTKCONTRIB:BOOL=ON -DQT_VTK:BOOL=ON"